version: '3'

services:
  db:
    image: mysql
    volumes:
     - db_data:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "qtc"
    ports:
      - "2051:80"
  web:
    depends_on:
      - db
    build: .
    volumes:
      - ".:/src"
    ports:
      - "3030:2050"
    restart: always
volumes:
    db_data: